/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-17 05:36:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Get session variables
    String username = (String) session.getAttribute("username");
    Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
    if (isLoggedIn == null) isLoggedIn = false;
    
    // Get current page for active link highlighting
    String currentPage = request.getRequestURI();
    String contextPath = request.getContextPath();
    
    // Navigation items configuration
    Map<String, String> navItems = new LinkedHashMap<>();
    navItems.put("index.jsp", "Home");
    navItems.put("category.jsp", "Categories");
    navItems.put("product.jsp?category=Electronics", "Products");
    navItems.put("cart.jsp", "Cart");
    navItems.put("about.jsp", "About");
    navItems.put("contact.jsp", "Contact");
    
    // Get cart count if available
    List<Map<String, String>> cart = (List<Map<String, String>>) session.getAttribute("cart");
    int cartCount = (cart != null) ? cart.size() : 0;
    
    // Get any success/error messages
    String message = request.getParameter("message");
    String error = request.getParameter("error");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Success/Error Messages -->\r\n");
 if (message != null && !message.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("<div class=\"alert-container\">\r\n");
      out.write("    <div class=\"alert alert-success alert-dismissible\">\r\n");
      out.write("        <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("        ");
      out.print( message );
      out.write("\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" onclick=\"this.parentElement.parentElement.style.display='none'\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if (error != null && !error.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("<div class=\"alert-container\">\r\n");
      out.write("    <div class=\"alert alert-danger alert-dismissible\">\r\n");
      out.write("        <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("        ");
      out.print( error );
      out.write("\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" onclick=\"this.parentElement.parentElement.style.display='none'\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\">\r\n");
      out.write("    <div class=\"container-fluid nav-container\">\r\n");
      out.write("        <!-- Brand -->\r\n");
      out.write("        <a class=\"nav-brand\" href=\"index.jsp\">\r\n");
      out.write("            <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("            <span>ShopEasy</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Search Bar (Desktop) -->\r\n");
      out.write("        <div class=\"nav-search d-none d-lg-flex\">\r\n");
      out.write("            <form action=\"search.jsp\" method=\"GET\" class=\"search-form\">\r\n");
      out.write("                <input type=\"text\" name=\"q\" placeholder=\"Search products...\" class=\"search-input\" \r\n");
      out.write("                       value=\"");
      out.print( request.getParameter("q") != null ? request.getParameter("q") : "" );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"search-btn\">\r\n");
      out.write("                    <i class=\"fas fa-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Desktop Navigation Links -->\r\n");
      out.write("        <div class=\"nav-links d-none d-lg-flex\">\r\n");
      out.write("            ");
 for (Map.Entry<String, String> item : navItems.entrySet()) { 
                String href = item.getKey();
                String label = item.getValue();
                boolean isActive = currentPage.contains(href.split("\\?")[0]);
            
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( href );
      out.write("\" class=\"nav-link ");
      out.print( isActive ? "active" : "" );
      out.write("\">\r\n");
      out.write("                    ");
      out.print( label );
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- User Actions (Desktop) -->\r\n");
      out.write("        <div class=\"nav-actions d-none d-lg-flex\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-icon\" title=\"Wishlist\" onclick=\"showComingSoon('Wishlist')\">\r\n");
      out.write("                <i class=\"fas fa-heart\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-icon cart-icon\" title=\"Shopping Cart\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                ");
 if (cartCount > 0) { 
      out.write("\r\n");
      out.write("                    <span class=\"cart-badge\">");
      out.print( cartCount );
      out.write("</span>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                    <span class=\"welcome-text\">Welcome, ");
      out.print( username );
      out.write("!</span>\r\n");
      out.write("                    <div class=\"user-dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-icon\" title=\"Profile\">\r\n");
      out.write("                            <i class=\"fas fa-user-circle\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\" onclick=\"showComingSoon('Profile')\">\r\n");
      out.write("                                <i class=\"fas fa-user\"></i> Profile\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\" onclick=\"showComingSoon('Orders')\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-bag\"></i> Orders\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\" onclick=\"showComingSoon('Settings')\">\r\n");
      out.write("                                <i class=\"fas fa-cog\"></i> Settings\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                            <a href=\"logout.jsp\" class=\"dropdown-item\">\r\n");
      out.write("                                <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"nav-icon\" title=\"Login\">\r\n");
      out.write("                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Menu Button -->\r\n");
      out.write("        <button class=\"btn btn-outline-primary d-lg-none mobile-menu-btn\" type=\"button\" \r\n");
      out.write("                data-bs-toggle=\"offcanvas\" data-bs-target=\"#mobileNavigation\" \r\n");
      out.write("                aria-controls=\"mobileNavigation\" aria-label=\"Open navigation menu\">\r\n");
      out.write("            <i class=\"fas fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Navigation Offcanvas -->\r\n");
      out.write("<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"mobileNavigation\" aria-labelledby=\"mobileNavigationLabel\">\r\n");
      out.write("    <div class=\"offcanvas-header\">\r\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"mobileNavigationLabel\">\r\n");
      out.write("            <i class=\"fas fa-shopping-bag\"></i> ShopEasy\r\n");
      out.write("        </h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"offcanvas-body\">\r\n");
      out.write("        <!-- Mobile Search -->\r\n");
      out.write("        <div class=\"mobile-search mb-4\">\r\n");
      out.write("            <form action=\"search.jsp\" method=\"GET\" class=\"search-form\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search products...\" \r\n");
      out.write("                           value=\"");
      out.print( request.getParameter("q") != null ? request.getParameter("q") : "" );
      out.write("\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Navigation Links -->\r\n");
      out.write("        <nav class=\"mobile-nav\">\r\n");
      out.write("            ");
 for (Map.Entry<String, String> item : navItems.entrySet()) { 
                String href = item.getKey();
                String label = item.getValue();
                boolean isActive = currentPage.contains(href.split("\\?")[0]);
            
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( href );
      out.write("\" class=\"mobile-nav-link ");
      out.print( isActive ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                    ");
 if (href.equals("index.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-home\"></i>\r\n");
      out.write("                    ");
 } else if (href.equals("category.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("                    ");
 } else if (href.contains("product.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-box\"></i>\r\n");
      out.write("                    ");
 } else if (href.equals("cart.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                        ");
 if (cartCount > 0) { 
      out.write("\r\n");
      out.write("                            <span class=\"cart-badge\">");
      out.print( cartCount );
      out.write("</span>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
 } else if (href.equals("about.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-info-circle\"></i>\r\n");
      out.write("                    ");
 } else if (href.equals("contact.jsp")) { 
      out.write("\r\n");
      out.write("                        <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    ");
      out.print( label );
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile User Section -->\r\n");
      out.write("        <div class=\"mobile-user-section mt-auto\">\r\n");
      out.write("            <div class=\"mobile-actions\">\r\n");
      out.write("                <a href=\"#\" class=\"mobile-action-btn\" onclick=\"showComingSoon('Wishlist'); return false;\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                    <i class=\"fas fa-heart\"></i> Wishlist\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("                <div class=\"mobile-user-info\">\r\n");
      out.write("                    <div class=\"user-greeting\">\r\n");
      out.write("                        <i class=\"fas fa-user-circle\"></i>\r\n");
      out.write("                        <span>Welcome, ");
      out.print( username );
      out.write("!</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mobile-user-actions\">\r\n");
      out.write("                        <a href=\"#\" class=\"mobile-action-btn\" onclick=\"showComingSoon('Profile'); return false;\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                            <i class=\"fas fa-user\"></i> Profile\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\" class=\"mobile-action-btn\" onclick=\"showComingSoon('Orders'); return false;\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-bag\"></i> My Orders\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"logout.jsp\" class=\"mobile-action-btn logout-btn\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                            <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"mobile-auth-section\">\r\n");
      out.write("                    <a href=\"login.jsp\" class=\"btn btn-primary w-100 mb-2\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                        <i class=\"fas fa-sign-in-alt\"></i> Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"signup.jsp\" class=\"btn btn-outline-primary w-100\" data-bs-dismiss=\"offcanvas\">\r\n");
      out.write("                        <i class=\"fas fa-user-plus\"></i> Sign Up\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Include navigation fix script -->\r\n");
      out.write("<script src=\"js/navigation-fix.js\"></script>\r\n");
      out.write("<!-- Include app.js for smooth navigation -->\r\n");
      out.write("<script src=\"js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Show coming soon message for features not yet implemented\r\n");
      out.write("function showComingSoon(feature) {\r\n");
      out.write("    alert(feature + ' feature is coming soon! Stay tuned for updates.');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Auto-hide alerts after 5 seconds\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const alerts = document.querySelectorAll('.alert-container .alert');\r\n");
      out.write("    alerts.forEach(function(alert) {\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("            if (alert.parentElement) {\r\n");
      out.write("                alert.parentElement.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }, 5000);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
