/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-16 11:02:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>About Us - ShopEasy</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css?v=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        .about-hero {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 100px 0 60px 0;\n");
      out.write("            text-align: center;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .about-hero h1 {\n");
      out.write("            font-size: 3rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            animation: fadeInUp 0.7s;\n");
      out.write("        }\n");
      out.write("        .about-hero p {\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            animation: fadeInUp 1.1s;\n");
      out.write("        }\n");
      out.write("        .about-hero .about-icon {\n");
      out.write("            font-size: 4rem;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            color: #fff;\n");
      out.write("            animation: bounce 1.5s infinite alternate;\n");
      out.write("        }\n");
      out.write("        @keyframes bounce {\n");
      out.write("            0% { transform: translateY(0); }\n");
      out.write("            100% { transform: translateY(-20px); }\n");
      out.write("        }\n");
      out.write("        .about-section {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 40px rgba(102,126,234,0.08);\n");
      out.write("            padding: 50px 30px;\n");
      out.write("            margin-top: 25px;\n");
      out.write("            max-width: 900px;\n");
      out.write("            margin-left: auto;\n");
      out.write("            margin-right: auto;\n");
      out.write("            animation: fadeInUp 1.2s;\n");
      out.write("        }\n");
      out.write("        .about-features {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 30px;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-top: 40px;\n");
      out.write("        }\n");
      out.write("        .about-feature {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            border-radius: 15px;\n");
      out.write("            padding: 30px 25px;\n");
      out.write("            min-width: 220px;\n");
      out.write("            max-width: 300px;\n");
      out.write("            text-align: center;\n");
      out.write("            box-shadow: 0 5px 20px rgba(102,126,234,0.12);\n");
      out.write("            animation: fadeInUp 1.5s;\n");
      out.write("        }\n");
      out.write("        .about-feature i {\n");
      out.write("            font-size: 2.2rem;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .about-section { padding: 30px 10px; }\n");
      out.write("            .about-features { flex-direction: column; gap: 20px; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"nav-container\">\n");
      out.write("            <div class=\"nav-brand\">\n");
      out.write("                <i class=\"fas fa-shopping-bag\"></i>\n");
      out.write("                <span>ShopEasy</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-search d-none d-lg-flex\">\n");
      out.write("                <input type=\"text\" placeholder=\"Search products...\" class=\"search-input\">\n");
      out.write("                <button class=\"search-btn\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-links\">\n");
      out.write("                <a href=\"index.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                <a href=\"category.jsp\" class=\"nav-link\">Categories</a>\n");
      out.write("                <a href=\"product.jsp?category=Electronics\" class=\"nav-link\">Products</a>\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-link\">Cart</a>\n");
      out.write("                <a href=\"about.jsp\" class=\"nav-link active\">About</a>\n");
      out.write("                <a href=\"contact.jsp\" class=\"nav-link\">Contact</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-actions d-none d-lg-flex\">\n");
      out.write("                <a href=\"#\" class=\"nav-icon\" title=\"Wishlist\"><i class=\"fas fa-heart\"></i></a>\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-icon\" title=\"Shopping Cart\"><i class=\"fas fa-shopping-cart\"></i></a>\n");
      out.write("                <a href=\"login.jsp\" class=\"nav-icon\" title=\"Login\"><i class=\"fas fa-user\"></i></a>\n");
      out.write("            </div>\n");
      out.write("            <button class=\"btn d-lg-none\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#navOffcanvas\" aria-controls=\"navOffcanvas\" aria-label=\"Open menu\" style=\"margin-left: 38px;\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"navOffcanvas\" aria-labelledby=\"navOffcanvasLabel\">\n");
      out.write("        <div class=\"offcanvas-header\">\n");
      out.write("            <h5 class=\"offcanvas-title\" id=\"navOffcanvasLabel\">ShopEasy</h5>\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"offcanvas-body d-flex flex-column\">\n");
      out.write("            <div class=\"mb-3\">\n");
      out.write("                <div class=\"d-flex align-items-center p-2 rounded\" style=\"background:#f8f9fa;\">\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control-sm me-2\" placeholder=\"Search products...\" id=\"offcanvasSearchInput\">\n");
      out.write("                    <button class=\"btn btn-primary btn-sm\" id=\"offcanvasSearchBtn\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <nav class=\"nav flex-column mb-3\">\n");
      out.write("                <a href=\"index.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                <a href=\"category.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Categories</a>\n");
      out.write("                <a href=\"product.jsp?category=Electronics\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Products</a>\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Cart</a>\n");
      out.write("                <a href=\"about.jsp\" class=\"nav-link active\" data-bs-dismiss=\"offcanvas\">About</a>\n");
      out.write("                <a href=\"contact.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Contact</a>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"mt-auto d-flex align-items-center gap-3\">\n");
      out.write("                <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-heart\"></i></a>\n");
      out.write("                <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-shopping-cart\"></i></a>\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Login</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"about-hero\">\n");
      out.write("        <div class=\"about-icon\"><i class=\"fas fa-users\"></i></div>\n");
      out.write("        <h1>About ShopEasy</h1>\n");
      out.write("        <p>ShopEasy is your one-stop destination for a seamless, secure, and joyful online shopping experience. We bring you the best products, top brands, and unbeatable deals—all in one place.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"about-section\">\n");
      out.write("        <h2 class=\"mb-4\">Why Shop with Us?</h2>\n");
      out.write("        <div class=\"about-features\">\n");
      out.write("            <div class=\"about-feature\">\n");
      out.write("                <i class=\"fas fa-shipping-fast\"></i>\n");
      out.write("                <h5>Fast Delivery</h5>\n");
      out.write("                <p>Lightning-fast shipping to your doorstep, every time.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"about-feature\">\n");
      out.write("                <i class=\"fas fa-lock\"></i>\n");
      out.write("                <h5>Secure Payments</h5>\n");
      out.write("                <p>100% secure payment options for worry-free shopping.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"about-feature\">\n");
      out.write("                <i class=\"fas fa-headset\"></i>\n");
      out.write("                <h5>24/7 Support</h5>\n");
      out.write("                <p>Our support team is always here to help you, day or night.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"about-feature\">\n");
      out.write("                <i class=\"fas fa-tags\"></i>\n");
      out.write("                <h5>Best Deals</h5>\n");
      out.write("                <p>Unbeatable prices and exclusive offers on top products.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
