/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-17 06:30:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/head.jsp", Long.valueOf(1758089777997L));
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1758090382809L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

List<Map<String, String>> cart = (List<Map<String, String>>) session.getAttribute("cart");
if (cart == null) {
    cart = new ArrayList<>();
}

// Handle adding products to cart
if ("POST".equalsIgnoreCase(request.getMethod())) {
    String productId = request.getParameter("productId");
    String productName = request.getParameter("productName");
    String productPrice = request.getParameter("productPrice");
    String productImage = request.getParameter("productImage");
    
    if (productId != null && productName != null && productPrice != null && productImage != null) {
        // Check if product already exists in cart
        boolean found = false;
        for (Map<String, String> item : cart) {
            if (item.get("id").equals(productId)) {
                int quantity = Integer.parseInt(item.get("quantity"));
                item.put("quantity", String.valueOf(quantity + 1));
                found = true;
                break;
            }
        }
        
        if (!found) {
            Map<String, String> newItem = new HashMap<>();
            newItem.put("id", productId);
            newItem.put("name", productName);
            newItem.put("price", productPrice);
            newItem.put("image", productImage);
            newItem.put("quantity", "1");
            cart.add(newItem);
        }
        session.setAttribute("cart", cart);
    }
}

// Handle removing products from cart
String removeId = request.getParameter("removeId");
if (removeId != null) {
    cart.removeIf(item -> item.get("id").equals(removeId));
    session.setAttribute("cart", cart);
}

// Handle updating quantities
String updateId = request.getParameter("updateId");
String newQuantity = request.getParameter("newQuantity");
if (updateId != null && newQuantity != null) {
    try {
        int qty = Integer.parseInt(newQuantity);
        if (qty <= 0) {
            cart.removeIf(item -> item.get("id").equals(updateId));
        } else {
            for (Map<String, String> item : cart) {
                if (item.get("id").equals(updateId)) {
                    item.put("quantity", String.valueOf(qty));
                    break;
                }
            }
        }
        session.setAttribute("cart", cart);
    } catch (NumberFormatException e) {
        // Invalid quantity, ignore
    }
}

// Calculate total
double total = 0;
for (Map<String, String> item : cart) {
    String priceStr = item.get("price").replace("₹", "").replace(",", "");
    double price = Double.parseDouble(priceStr);
    int quantity = Integer.parseInt(item.get("quantity"));
    total += price * quantity;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Your Cart | ShopEasy</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css?v=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas {\r\n");
      out.write("        max-width: 85% !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        position: fixed !important;\r\n");
      out.write("        top: 0 !important;\r\n");
      out.write("        left: 0 !important;\r\n");
      out.write("        right: 0 !important;\r\n");
      out.write("        z-index: 1000 !important;\r\n");
      out.write("        border-bottom: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("        box-shadow: 0 2px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-container {\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-brand {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-brand i {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-search {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        margin: 0 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-input {\r\n");
      out.write("        border: none;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-btn {\r\n");
      out.write("        background: #667eea;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 5px 11px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link {\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color 0.3s ease;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover,\r\n");
      out.write("    .nav-link.active {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-actions {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-icon {\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-icon:hover {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        transform: scale(1.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-info {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .welcome-text {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        background: rgba(102, 126, 234, 0.1);\r\n");
      out.write("        padding: 5px 12px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .btn.d-lg-none {\r\n");
      out.write("        border: 1px solid #e2e8f0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 80px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        background: linear-gradient(135deg, #48bb78 0%, #38a169 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 15px 25px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 10px 25px rgba(72, 187, 120, 0.3);\r\n");
      out.write("        z-index: 1001;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        animation: slideDown 0.3s ease-out;\r\n");
      out.write("        max-width: 90%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message .close-btn {\r\n");
      out.write("        background: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        opacity: 0.8;\r\n");
      out.write("        transition: opacity 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message .close-btn:hover {\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slideDown {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateX(-50%) translateY(-20px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateX(-50%) translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Mobile First Responsive Design */\r\n");
      out.write("    @media (max-width: 1200px) {\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            padding: 0 15px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 992px) {\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: none !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mobile-menu-btn {\r\n");
      out.write("            display: block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-search {\r\n");
      out.write("            order: 3;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 15px 0 0 0;\r\n");
      out.write("            max-width: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-actions {\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message {\r\n");
      out.write("            top: 100px;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            transform: none;\r\n");
      out.write("            max-width: none;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message {\r\n");
      out.write("            top: 90px;\r\n");
      out.write("            left: 15px;\r\n");
      out.write("            right: 15px;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            padding: 8px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand i {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .custom-top{\r\n");
      out.write("            margin-top: 110px;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-item {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-item:hover {\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .product-image {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            max-height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .quantity-controls {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .quantity-btn {\r\n");
      out.write("            width: 35px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            border: 1px solid #dee2e6;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .quantity-btn:hover {\r\n");
      out.write("            background: #667eea;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("        }\r\n");
      out.write("        .quantity-input {\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border: 1px solid #dee2e6;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .section-title {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2d3748;\r\n");
      out.write("            margin-bottom: 50px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .section-title::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -10px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            padding: 8px 20px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            padding: 10px 25px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .total-section {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .empty-cart {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 60px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .empty-cart i {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            color: #dee2e6;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 1200px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                max-width: 100%;\r\n");
      out.write("                padding: 0 15px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 992px) {\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 2.2rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item .row {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item .col-md-2,\r\n");
      out.write("            .cart-item .col-md-4,\r\n");
      out.write("            .cart-item .col-md-3,\r\n");
      out.write("            .cart-item .col-md-1 {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                margin-bottom: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .product-image {\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .quantity-controls {\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 1.8rem;\r\n");
      out.write("                margin-bottom: 40px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .product-image {\r\n");
      out.write("                width: 120px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .total-section {\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                margin-top: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 0 10px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 1.6rem;\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item {\r\n");
      out.write("                padding: 15px 10px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .product-image {\r\n");
      out.write("                width: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item h5 {\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item h6 {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .quantity-btn {\r\n");
      out.write("                width: 30px;\r\n");
      out.write("                height: 30px;\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .quantity-input {\r\n");
      out.write("                width: 50px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn {\r\n");
      out.write("                padding: 8px 16px;\r\n");
      out.write("                font-size: 13px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .total-section {\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .empty-cart i {\r\n");
      out.write("                font-size: 3rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .section-title {\r\n");
      out.write("                font-size: 1.4rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item {\r\n");
      out.write("                padding: 12px 8px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .product-image {\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item h5 {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item h6 {\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .quantity-btn {\r\n");
      out.write("                width: 25px;\r\n");
      out.write("                height: 25px;\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .quantity-input {\r\n");
      out.write("                width: 40px;\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn {\r\n");
      out.write("                padding: 6px 12px;\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .empty-cart i {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 360px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 0 5px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .cart-item {\r\n");
      out.write("                padding: 10px 5px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .product-image {\r\n");
      out.write("                width: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn {\r\n");
      out.write("                padding: 5px 10px;\r\n");
      out.write("                font-size: 11px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

    // Check if user session variables exist, if not set defaults
    if (session.getAttribute("username") == null) {
        session.setAttribute("username", null);
    }
    if (session.getAttribute("isLoggedIn") == null) {
        session.setAttribute("isLoggedIn", false);
    }

      out.write("\r\n");
      out.write("\r\n");
 if (request.getParameter("message") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"success-message\">\r\n");
      out.write("        <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("        ");
      out.print( request.getParameter("message") );
      out.write("\r\n");
      out.write("        <button onclick=\"this.parentElement.style.display='none'\" class=\"close-btn\">&times;</button>\r\n");
      out.write("    </div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("    <div class=\"nav-container\">\r\n");
      out.write("        <div class=\"nav-brand\">\r\n");
      out.write("            <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("            <span>ShopEasy</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-search d-none d-lg-flex\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search products...\" class=\"search-input\">\r\n");
      out.write("            <button class=\"search-btn\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\">Home</a>\r\n");
      out.write("            <a href=\"category.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("category.jsp") ? "active" : "" );
      out.write("\">Categories</a>\r\n");
      out.write("            <a href=\"product.jsp?category=Electronics\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("product.jsp") ? "active" : "" );
      out.write("\">Products</a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\">Cart</a>\r\n");
      out.write("            <a href=\"about.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\">About</a>\r\n");
      out.write("            <a href=\"contact.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\">Contact</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-actions d-none d-lg-flex\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-icon\" title=\"Wishlist\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-icon\" title=\"Shopping Cart\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("            ");
 if (session.getAttribute("isLoggedIn") != null && (Boolean) session.getAttribute("isLoggedIn")) { 
      out.write("\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                    <span class=\"welcome-text\">Welcome, ");
      out.print( session.getAttribute("username") );
      out.write("!</span>\r\n");
      out.write("                    <a href=\"logout.jsp\" class=\"nav-icon\" title=\"Logout\"><i class=\"fas fa-sign-out-alt\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"nav-icon\" title=\"Login\"><i class=\"fas fa-user\"></i></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"btn d-lg-none\" type=\"button\" data-bs-toggle=\"offcanvas\"\r\n");
      out.write("            data-bs-target=\"#navOffcanvas\" aria-controls=\"navOffcanvas\" aria-label=\"Open menu\"\r\n");
      out.write("            style=\"margin-left: 38px;\">\r\n");
      out.write("            <i class=\"fas fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Navigation Offcanvas -->\r\n");
      out.write("<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"navOffcanvas\" aria-labelledby=\"navOffcanvasLabel\">\r\n");
      out.write("    <div class=\"offcanvas-header\">\r\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"navOffcanvasLabel\">ShopEasy</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"offcanvas-body d-flex flex-column\">\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <div class=\"d-flex align-items-center p-2 rounded\" style=\"background:#f8f9fa;\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control-sm me-2\"\r\n");
      out.write("                    placeholder=\"Search products...\" id=\"offcanvasSearchInput\">\r\n");
      out.write("                <button class=\"btn btn-primary btn-sm\" id=\"offcanvasSearchBtn\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav flex-column mb-3\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Home</a>\r\n");
      out.write("            <a href=\"category.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("category.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Categories</a>\r\n");
      out.write("            <a href=\"product.jsp?category=Electronics\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("product.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Products</a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Cart</a>\r\n");
      out.write("            <a href=\"about.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">About</a>\r\n");
      out.write("            <a href=\"contact.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Contact</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"mt-auto d-flex align-items-center gap-3\">\r\n");
      out.write("            <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"text-secondary\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("            ");
 if (session.getAttribute("isLoggedIn") != null && (Boolean) session.getAttribute("isLoggedIn")) { 
      out.write("\r\n");
      out.write("                <span class=\"text-primary fw-semibold\">Welcome, ");
      out.print( session.getAttribute("username") );
      out.write("</span>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn btn-outline-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Logout</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Login</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container custom-top\">\r\n");
      out.write("        <h1 class=\"section-title\">Your Shopping Cart</h1>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(cart.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"empty-cart\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                <h3>Your cart is empty</h3>\r\n");
      out.write("                <p class=\"text-muted\">Add some products to get started!</p>\r\n");
      out.write("                <a href=\"category.jsp\" class=\"btn btn-primary mt-3\">Start Shopping</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    ");
 for(Map<String, String> item : cart) { 
      out.write("\r\n");
      out.write("                    <div class=\"cart-item mb-4 p-4\">\r\n");
      out.write("                        <div class=\"row align-items-center\">\r\n");
      out.write("                            <div class=\"col-md-2\">\r\n");
      out.write("                                <img src=\"");
      out.print(item.get("image"));
      out.write("\" alt=\"");
      out.print(item.get("name"));
      out.write("\" class=\"product-image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <h5 class=\"mb-1\">");
      out.print(item.get("name"));
      out.write("</h5>\r\n");
      out.write("                                <p class=\"text-muted mb-0\">Product ID: ");
      out.print(item.get("id"));
      out.write("</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2\">\r\n");
      out.write("                                <h6 class=\"text-black mb-0\">");
      out.print(item.get("price"));
      out.write("</h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"quantity-controls\">\r\n");
      out.write("                                    <form action=\"cart.jsp\" method=\"post\" class=\"d-inline\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"updateId\" value=\"");
      out.print(item.get("id"));
      out.write("\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"newQuantity\" value=\"");
      out.print(Integer.parseInt(item.get("quantity")) - 1);
      out.write("\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"quantity-btn\" ");
      out.print(Integer.parseInt(item.get("quantity")) <= 1 ? "disabled" : "");
      out.write(">\r\n");
      out.write("                                            <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                    <input type=\"number\" value=\"");
      out.print(item.get("quantity"));
      out.write("\" class=\"quantity-input\" \r\n");
      out.write("                                           onchange=\"updateQuantity('");
      out.print(item.get("id"));
      out.write("', this.value)\" min=\"1\">\r\n");
      out.write("                                    <form action=\"cart.jsp\" method=\"post\" class=\"d-inline\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"updateId\" value=\"");
      out.print(item.get("id"));
      out.write("\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"newQuantity\" value=\"");
      out.print(Integer.parseInt(item.get("quantity")) + 1);
      out.write("\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"quantity-btn\">\r\n");
      out.write("                                            <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-1\">\r\n");
      out.write("                                <form action=\"cart.jsp\" method=\"post\" class=\"d-inline\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"removeId\" value=\"");
      out.print(item.get("id"));
      out.write("\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger btn-sm\" \r\n");
      out.write("                                            onclick=\"return confirm('Remove this item from cart?')\">\r\n");
      out.write("                                        <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"total-section\">\r\n");
      out.write("                        <h4 class=\"mb-4\">Order Summary</h4>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("                            <span>Items (");
      out.print(cart.size());
      out.write("):</span>\r\n");
      out.write("                            <span>₹");
      out.print(String.format("%.2f", total));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("                            <span>Shipping:</span>\r\n");
      out.write("                            <span class=\"text-success\">Free</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("                            <span>GST (18%):</span>\r\n");
      out.write("                            <span>₹");
      out.print(String.format("%.2f", total * 0.18));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-4\">\r\n");
      out.write("                            <h5>Total:</h5>\r\n");
      out.write("                            <h5 class=\"text-black\">₹");
      out.print(String.format("%.2f", total + (total * 0.18)));
      out.write("</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"payment.jsp\" class=\"btn btn-primary w-100 mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-credit-card me-2\"></i>Proceed to Payment\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"category.jsp\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                            <i class=\"fas fa-arrow-left me-2\"></i>Continue Shopping\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function updateQuantity(productId, newQuantity) {\r\n");
      out.write("            if (newQuantity < 1) {\r\n");
      out.write("                if (confirm('Remove this item from cart?')) {\r\n");
      out.write("                    document.querySelector(`form input[name=\"removeId\"][value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`).closest('form').submit();\r\n");
      out.write("                } else {\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                const form = document.createElement('form');\r\n");
      out.write("                form.method = 'post';\r\n");
      out.write("                form.action = 'cart.jsp';\r\n");
      out.write("                \r\n");
      out.write("                const updateIdInput = document.createElement('input');\r\n");
      out.write("                updateIdInput.type = 'hidden';\r\n");
      out.write("                updateIdInput.name = 'updateId';\r\n");
      out.write("                updateIdInput.value = productId;\r\n");
      out.write("                \r\n");
      out.write("                const newQuantityInput = document.createElement('input');\r\n");
      out.write("                newQuantityInput.type = 'hidden';\r\n");
      out.write("                newQuantityInput.name = 'newQuantity';\r\n");
      out.write("                newQuantityInput.value = newQuantity;\r\n");
      out.write("                \r\n");
      out.write("                form.appendChild(updateIdInput);\r\n");
      out.write("                form.appendChild(newQuantityInput);\r\n");
      out.write("                document.body.appendChild(form);\r\n");
      out.write("                form.submit();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
