/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-17 06:31:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/head.jsp", Long.valueOf(1758089777997L));
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1758090666876L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

// Get cart from session
List<Map<String, String>> cart = (List<Map<String, String>>) session.getAttribute("cart");
if (cart == null) {
    cart = new ArrayList<>();
}

// Calculate total
double total = 0;
for (Map<String, String> item : cart) {
    String priceStr = item.get("price").replace("₹", "").replace(",", "");
    double price = Double.parseDouble(priceStr);
    int quantity = Integer.parseInt(item.get("quantity"));
    total += price * quantity;
}

// Get user info
String username = (String) session.getAttribute("username");
Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
if (isLoggedIn == null) isLoggedIn = false;

// For demo purposes, allow guest checkout
if (!isLoggedIn) {
    username = "Guest User";
}

// Redirect to cart if empty
if (cart.isEmpty()) {
    response.sendRedirect("cart.jsp");
    return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Secure Payment - ShopEasy</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css?v=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas {\r\n");
      out.write("        max-width: 85% !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        position: fixed !important;\r\n");
      out.write("        top: 0 !important;\r\n");
      out.write("        left: 0 !important;\r\n");
      out.write("        right: 0 !important;\r\n");
      out.write("        z-index: 1000 !important;\r\n");
      out.write("        border-bottom: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("        box-shadow: 0 2px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-container {\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-brand {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-brand i {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-search {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        margin: 0 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-input {\r\n");
      out.write("        border: none;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-btn {\r\n");
      out.write("        background: #667eea;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 5px 11px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link {\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        transition: color 0.3s ease;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover,\r\n");
      out.write("    .nav-link.active {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-actions {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-icon {\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-icon:hover {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        transform: scale(1.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-info {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .welcome-text {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        background: rgba(102, 126, 234, 0.1);\r\n");
      out.write("        padding: 5px 12px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .btn.d-lg-none {\r\n");
      out.write("        border: 1px solid #e2e8f0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 80px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        background: linear-gradient(135deg, #48bb78 0%, #38a169 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 15px 25px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 10px 25px rgba(72, 187, 120, 0.3);\r\n");
      out.write("        z-index: 1001;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        animation: slideDown 0.3s ease-out;\r\n");
      out.write("        max-width: 90%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message .close-btn {\r\n");
      out.write("        background: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        opacity: 0.8;\r\n");
      out.write("        transition: opacity 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .success-message .close-btn:hover {\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slideDown {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateX(-50%) translateY(-20px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateX(-50%) translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Mobile First Responsive Design */\r\n");
      out.write("    @media (max-width: 1200px) {\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            padding: 0 15px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 992px) {\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: none !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mobile-menu-btn {\r\n");
      out.write("            display: block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-search {\r\n");
      out.write("            order: 3;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 15px 0 0 0;\r\n");
      out.write("            max-width: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-actions {\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message {\r\n");
      out.write("            top: 100px;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            transform: none;\r\n");
      out.write("            max-width: none;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message {\r\n");
      out.write("            top: 90px;\r\n");
      out.write("            left: 15px;\r\n");
      out.write("            right: 15px;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            padding: 8px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-brand i {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .payment-container {\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            min-height: 90vh;\r\n");
      out.write("            padding: 40px 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-header {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-header h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-header .secure-badge {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            padding: 5px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-methods {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .method-tabs {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            border-bottom: 2px solid #e9ecef;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .method-tab {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            min-width: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .method-tab.active {\r\n");
      out.write("            border-bottom: 3px solid #667eea;\r\n");
      out.write("            color: #667eea;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .method-tab:hover {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .payment-content.active {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2d3748;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-col {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-icons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-icon {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #667eea;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .upi-options {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .upi-option {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .upi-option:hover,\r\n");
      out.write("        .upi-option.selected {\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("            background: rgba(102, 126, 234, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .upi-option img {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .bank-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .bank-option {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .bank-option:hover,\r\n");
      out.write("        .bank-option.selected {\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("            background: rgba(102, 126, 234, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .order-summary {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .summary-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .summary-total {\r\n");
      out.write("            border-top: 2px solid #e2e8f0;\r\n");
      out.write("            padding-top: 15px;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .pay-button {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .pay-button:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .security-features {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .security-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            color: #28a745;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .loading-overlay {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.8);\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .loading-content {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .spinner {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border: 5px solid #f3f3f3;\r\n");
      out.write("            border-top: 5px solid #667eea;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: spin 1s linear infinite;\r\n");
      out.write("            margin: 0 auto 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            0% { transform: rotate(0deg); }\r\n");
      out.write("            100% { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .payment-container {\r\n");
      out.write("                padding: 20px 0;\r\n");
      out.write("                margin-top: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .method-tabs {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .method-tab {\r\n");
      out.write("                flex: none;\r\n");
      out.write("                margin-bottom: 5px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .form-row {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .upi-options {\r\n");
      out.write("                grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .bank-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .security-features {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 15px;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .payment-methods {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .payment-header {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

    // Check if user session variables exist, if not set defaults
    if (session.getAttribute("username") == null) {
        session.setAttribute("username", null);
    }
    if (session.getAttribute("isLoggedIn") == null) {
        session.setAttribute("isLoggedIn", false);
    }

      out.write("\r\n");
      out.write("\r\n");
 if (request.getParameter("message") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"success-message\">\r\n");
      out.write("        <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("        ");
      out.print( request.getParameter("message") );
      out.write("\r\n");
      out.write("        <button onclick=\"this.parentElement.style.display='none'\" class=\"close-btn\">&times;</button>\r\n");
      out.write("    </div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("    <div class=\"nav-container\">\r\n");
      out.write("        <div class=\"nav-brand\">\r\n");
      out.write("            <i class=\"fas fa-shopping-bag\"></i>\r\n");
      out.write("            <span>ShopEasy</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-search d-none d-lg-flex\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search products...\" class=\"search-input\">\r\n");
      out.write("            <button class=\"search-btn\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\">Home</a>\r\n");
      out.write("            <a href=\"category.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("category.jsp") ? "active" : "" );
      out.write("\">Categories</a>\r\n");
      out.write("            <a href=\"product.jsp?category=Electronics\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("product.jsp") ? "active" : "" );
      out.write("\">Products</a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\">Cart</a>\r\n");
      out.write("            <a href=\"about.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\">About</a>\r\n");
      out.write("            <a href=\"contact.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\">Contact</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav-actions d-none d-lg-flex\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-icon\" title=\"Wishlist\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-icon\" title=\"Shopping Cart\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("            ");
 if (session.getAttribute("isLoggedIn") != null && (Boolean) session.getAttribute("isLoggedIn")) { 
      out.write("\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                    <span class=\"welcome-text\">Welcome, ");
      out.print( session.getAttribute("username") );
      out.write("!</span>\r\n");
      out.write("                    <a href=\"logout.jsp\" class=\"nav-icon\" title=\"Logout\"><i class=\"fas fa-sign-out-alt\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"nav-icon\" title=\"Login\"><i class=\"fas fa-user\"></i></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"btn d-lg-none\" type=\"button\" data-bs-toggle=\"offcanvas\"\r\n");
      out.write("            data-bs-target=\"#navOffcanvas\" aria-controls=\"navOffcanvas\" aria-label=\"Open menu\"\r\n");
      out.write("            style=\"margin-left: 38px;\">\r\n");
      out.write("            <i class=\"fas fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Navigation Offcanvas -->\r\n");
      out.write("<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"navOffcanvas\" aria-labelledby=\"navOffcanvasLabel\">\r\n");
      out.write("    <div class=\"offcanvas-header\">\r\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"navOffcanvasLabel\">ShopEasy</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"offcanvas-body d-flex flex-column\">\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <div class=\"d-flex align-items-center p-2 rounded\" style=\"background:#f8f9fa;\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control-sm me-2\"\r\n");
      out.write("                    placeholder=\"Search products...\" id=\"offcanvasSearchInput\">\r\n");
      out.write("                <button class=\"btn btn-primary btn-sm\" id=\"offcanvasSearchBtn\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"nav flex-column mb-3\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Home</a>\r\n");
      out.write("            <a href=\"category.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("category.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Categories</a>\r\n");
      out.write("            <a href=\"product.jsp?category=Electronics\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("product.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Products</a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Cart</a>\r\n");
      out.write("            <a href=\"about.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">About</a>\r\n");
      out.write("            <a href=\"contact.jsp\" class=\"nav-link ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" data-bs-dismiss=\"offcanvas\">Contact</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"mt-auto d-flex align-items-center gap-3\">\r\n");
      out.write("            <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("            <a href=\"cart.jsp\" class=\"text-secondary\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("            ");
 if (session.getAttribute("isLoggedIn") != null && (Boolean) session.getAttribute("isLoggedIn")) { 
      out.write("\r\n");
      out.write("                <span class=\"text-primary fw-semibold\">Welcome, ");
      out.print( session.getAttribute("username") );
      out.write("</span>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn btn-outline-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Logout</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Login</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"payment-container\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"payment-card\">\r\n");
      out.write("                        <div class=\"payment-header\">\r\n");
      out.write("                            <h2><i class=\"fas fa-shield-alt me-2\"></i>Secure Payment</h2>\r\n");
      out.write("                            <div class=\"secure-badge\">\r\n");
      out.write("                                <i class=\"fas fa-lock me-1\"></i>256-bit SSL Encrypted\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"payment-methods\">\r\n");
      out.write("                            <!-- Order Summary -->\r\n");
      out.write("                            <div class=\"order-summary\">\r\n");
      out.write("                                <h5 class=\"mb-3\"><i class=\"fas fa-receipt me-2\"></i>Order Summary</h5>\r\n");
      out.write("                                ");
 for(Map<String, String> item : cart) { 
      out.write("\r\n");
      out.write("                                    <div class=\"summary-row\">\r\n");
      out.write("                                        <span>");
      out.print(item.get("name"));
      out.write(' ');
      out.write('×');
      out.write(' ');
      out.print(item.get("quantity"));
      out.write("</span>\r\n");
      out.write("                                        <span>₹");
      out.print(String.format("%.2f", Double.parseDouble(item.get("price").replace("₹", "").replace(",", "")) * Integer.parseInt(item.get("quantity"))));
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                <div class=\"summary-row\">\r\n");
      out.write("                                    <span>Shipping</span>\r\n");
      out.write("                                    <span class=\"text-success\">Free</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"summary-row\">\r\n");
      out.write("                                    <span>GST (18%)</span>\r\n");
      out.write("                                    <span>₹");
      out.print(String.format("%.2f", total * 0.18));
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"summary-row summary-total\">\r\n");
      out.write("                                    <span>Total Amount</span>\r\n");
      out.write("                                    <span>₹");
      out.print(String.format("%.2f", total + (total * 0.18)));
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Payment Method Tabs -->\r\n");
      out.write("                            <div class=\"method-tabs\">\r\n");
      out.write("                                <button class=\"method-tab active\" onclick=\"showPaymentMethod('card')\">\r\n");
      out.write("                                    <i class=\"fas fa-credit-card mb-1\"></i><br>Credit/Debit Card\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"method-tab\" onclick=\"showPaymentMethod('upi')\">\r\n");
      out.write("                                    <i class=\"fas fa-mobile-alt mb-1\"></i><br>UPI\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"method-tab\" onclick=\"showPaymentMethod('netbanking')\">\r\n");
      out.write("                                    <i class=\"fas fa-university mb-1\"></i><br>Net Banking\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"method-tab\" onclick=\"showPaymentMethod('wallet')\">\r\n");
      out.write("                                    <i class=\"fas fa-wallet mb-1\"></i><br>Wallet\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Credit/Debit Card -->\r\n");
      out.write("                            <div id=\"card\" class=\"payment-content active\">\r\n");
      out.write("                                <form id=\"cardForm\" onsubmit=\"processPayment(event, 'card')\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"form-label\">Card Number</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"1234 5678 9012 3456\" \r\n");
      out.write("                                               maxlength=\"19\" oninput=\"formatCardNumber(this)\" required>\r\n");
      out.write("                                        <div class=\"card-icons\">\r\n");
      out.write("                                            <div class=\"card-icon\">VISA</div>\r\n");
      out.write("                                            <div class=\"card-icon\">MC</div>\r\n");
      out.write("                                            <div class=\"card-icon\">AMEX</div>\r\n");
      out.write("                                            <div class=\"card-icon\">RUPAY</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"form-label\">Cardholder Name</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"John Doe\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-row\">\r\n");
      out.write("                                        <div class=\"form-col\">\r\n");
      out.write("                                            <label class=\"form-label\">Expiry Date</label>\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"MM/YY\" \r\n");
      out.write("                                                   maxlength=\"5\" oninput=\"formatExpiry(this)\" required>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-col\">\r\n");
      out.write("                                            <label class=\"form-label\">CVV</label>\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" placeholder=\"123\" \r\n");
      out.write("                                                   maxlength=\"4\" required>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"pay-button\">\r\n");
      out.write("                                        <i class=\"fas fa-lock me-2\"></i>Pay ₹");
      out.print(String.format("%.2f", total + (total * 0.18)));
      out.write("\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- UPI -->\r\n");
      out.write("                            <div id=\"upi\" class=\"payment-content\">\r\n");
      out.write("                                <form id=\"upiForm\" onsubmit=\"processPayment(event, 'upi')\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"form-label\">UPI ID</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"yourname@paytm\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"upi-options\">\r\n");
      out.write("                                        <div class=\"upi-option\" onclick=\"selectUpiApp('googlepay')\">\r\n");
      out.write("                                            <div style=\"width:40px; height:40px; background:#4285f4; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">G</div>\r\n");
      out.write("                                            <div>Google Pay</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"upi-option\" onclick=\"selectUpiApp('phonepe')\">\r\n");
      out.write("                                            <div style=\"width:40px; height:40px; background:#5f259f; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">P</div>\r\n");
      out.write("                                            <div>PhonePe</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"upi-option\" onclick=\"selectUpiApp('paytm')\">\r\n");
      out.write("                                            <div style=\"width:40px; height:40px; background:#00baf2; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">P</div>\r\n");
      out.write("                                            <div>Paytm</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"upi-option\" onclick=\"selectUpiApp('bhim')\">\r\n");
      out.write("                                            <div style=\"width:40px; height:40px; background:#ff6600; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">B</div>\r\n");
      out.write("                                            <div>BHIM UPI</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"pay-button\">\r\n");
      out.write("                                        <i class=\"fas fa-mobile-alt me-2\"></i>Pay with UPI\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Net Banking -->\r\n");
      out.write("                            <div id=\"netbanking\" class=\"payment-content\">\r\n");
      out.write("                                <form id=\"netbankingForm\" onsubmit=\"processPayment(event, 'netbanking')\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"form-label\">Select Your Bank</label>\r\n");
      out.write("                                        <select class=\"form-control\" required>\r\n");
      out.write("                                            <option value=\"\">Choose your bank</option>\r\n");
      out.write("                                            <option value=\"sbi\">State Bank of India</option>\r\n");
      out.write("                                            <option value=\"hdfc\">HDFC Bank</option>\r\n");
      out.write("                                            <option value=\"icici\">ICICI Bank</option>\r\n");
      out.write("                                            <option value=\"axis\">Axis Bank</option>\r\n");
      out.write("                                            <option value=\"kotak\">Kotak Mahindra Bank</option>\r\n");
      out.write("                                            <option value=\"pnb\">Punjab National Bank</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"bank-grid\">\r\n");
      out.write("                                        <div class=\"bank-option\" onclick=\"selectBank('sbi')\">\r\n");
      out.write("                                            <strong>SBI</strong><br>\r\n");
      out.write("                                            <small>State Bank of India</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bank-option\" onclick=\"selectBank('hdfc')\">\r\n");
      out.write("                                            <strong>HDFC</strong><br>\r\n");
      out.write("                                            <small>HDFC Bank</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bank-option\" onclick=\"selectBank('icici')\">\r\n");
      out.write("                                            <strong>ICICI</strong><br>\r\n");
      out.write("                                            <small>ICICI Bank</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bank-option\" onclick=\"selectBank('axis')\">\r\n");
      out.write("                                            <strong>AXIS</strong><br>\r\n");
      out.write("                                            <small>Axis Bank</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"pay-button\">\r\n");
      out.write("                                        <i class=\"fas fa-university me-2\"></i>Pay with Net Banking\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Wallet -->\r\n");
      out.write("                            <div id=\"wallet\" class=\"payment-content\">\r\n");
      out.write("                                <form id=\"walletForm\" onsubmit=\"processPayment(event, 'wallet')\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"form-label\">Select Wallet</label>\r\n");
      out.write("                                        <div class=\"upi-options\">\r\n");
      out.write("                                            <div class=\"upi-option\" onclick=\"selectWallet('paytm')\">\r\n");
      out.write("                                                <div style=\"width:40px; height:40px; background:#00baf2; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">P</div>\r\n");
      out.write("                                                <div>Paytm Wallet</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"upi-option\" onclick=\"selectWallet('freecharge')\">\r\n");
      out.write("                                                <div style=\"width:40px; height:40px; background:#00c853; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">F</div>\r\n");
      out.write("                                                <div>FreeCharge</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"upi-option\" onclick=\"selectWallet('mobikwik')\">\r\n");
      out.write("                                                <div style=\"width:40px; height:40px; background:#e91e63; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">M</div>\r\n");
      out.write("                                                <div>MobiKwik</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"upi-option\" onclick=\"selectWallet('amazon')\">\r\n");
      out.write("                                                <div style=\"width:40px; height:40px; background:#ff9900; border-radius:50%; margin:0 auto 8px; display:flex; align-items:center; justify-content:center; color:white; font-weight:bold;\">A</div>\r\n");
      out.write("                                                <div>Amazon Pay</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"pay-button\">\r\n");
      out.write("                                        <i class=\"fas fa-wallet me-2\"></i>Pay with Wallet\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Security Features -->\r\n");
      out.write("                            <div class=\"security-features\">\r\n");
      out.write("                                <div class=\"security-item\">\r\n");
      out.write("                                    <i class=\"fas fa-shield-alt\"></i>\r\n");
      out.write("                                    <span>SSL Secure</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"security-item\">\r\n");
      out.write("                                    <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                                    <span>Bank Level Security</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"security-item\">\r\n");
      out.write("                                    <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                                    <span>PCI DSS Compliant</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Loading Overlay -->\r\n");
      out.write("    <div id=\"loadingOverlay\" class=\"loading-overlay\">\r\n");
      out.write("        <div class=\"loading-content\">\r\n");
      out.write("            <div class=\"spinner\"></div>\r\n");
      out.write("            <h4>Processing Payment...</h4>\r\n");
      out.write("            <p>Please do not refresh or close this window</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        function showPaymentMethod(method) {\r\n");
      out.write("            // Hide all content\r\n");
      out.write("            document.querySelectorAll('.payment-content').forEach(content => {\r\n");
      out.write("                content.classList.remove('active');\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // Remove active class from all tabs\r\n");
      out.write("            document.querySelectorAll('.method-tab').forEach(tab => {\r\n");
      out.write("                tab.classList.remove('active');\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // Show selected content and activate tab\r\n");
      out.write("            document.getElementById(method).classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            // Find and activate the clicked tab\r\n");
      out.write("            const clickedTab = event ? event.target.closest('.method-tab') : document.querySelector('.method-tab');\r\n");
      out.write("            if (clickedTab) {\r\n");
      out.write("                clickedTab.classList.add('active');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function formatCardNumber(input) {\r\n");
      out.write("            let value = input.value.replace(/\\s/g, '').replace(/[^0-9]/gi, '');\r\n");
      out.write("            let formattedValue = value.match(/.{1,4}/g)?.join(' ') || value;\r\n");
      out.write("            input.value = formattedValue;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function formatExpiry(input) {\r\n");
      out.write("            let value = input.value.replace(/\\D/g, '');\r\n");
      out.write("            if (value.length >= 2) {\r\n");
      out.write("                value = value.substring(0,2) + '/' + value.substring(2,4);\r\n");
      out.write("            }\r\n");
      out.write("            input.value = value;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function selectUpiApp(app) {\r\n");
      out.write("            document.querySelectorAll('.upi-option').forEach(option => {\r\n");
      out.write("                option.classList.remove('selected');\r\n");
      out.write("            });\r\n");
      out.write("            event.currentTarget.classList.add('selected');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function selectBank(bank) {\r\n");
      out.write("            document.querySelectorAll('.bank-option').forEach(option => {\r\n");
      out.write("                option.classList.remove('selected');\r\n");
      out.write("            });\r\n");
      out.write("            event.currentTarget.classList.add('selected');\r\n");
      out.write("            \r\n");
      out.write("            // Update select dropdown\r\n");
      out.write("            document.querySelector('#netbanking select').value = bank;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function selectWallet(wallet) {\r\n");
      out.write("            document.querySelectorAll('#wallet .upi-option').forEach(option => {\r\n");
      out.write("                option.classList.remove('selected');\r\n");
      out.write("            });\r\n");
      out.write("            event.currentTarget.classList.add('selected');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function processPayment(event, method) {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            console.log('Processing payment with method:', method);\r\n");
      out.write("            \r\n");
      out.write("            // Show loading overlay\r\n");
      out.write("            document.getElementById('loadingOverlay').style.display = 'flex';\r\n");
      out.write("            \r\n");
      out.write("            // Simulate payment processing\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                // Generate random payment ID\r\n");
      out.write("                const paymentId = 'PAY_' + Math.random().toString(36).substring(2, 15).toUpperCase();\r\n");
      out.write("                const totalAmount = '");
      out.print(String.format("%.2f", total + (total * 0.18)));
      out.write("';\r\n");
      out.write("                \r\n");
      out.write("                console.log('Redirecting to success page with:', {\r\n");
      out.write("                    paymentId: paymentId,\r\n");
      out.write("                    method: method,\r\n");
      out.write("                    amount: totalAmount\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                // Redirect to success page with clear cart parameter\r\n");
      out.write("                const successUrl = 'payment-success.jsp?payment_id=' + paymentId + '&method=' + method + '&amount=' + totalAmount + '&clear_cart=true';\r\n");
      out.write("                console.log('Success URL:', successUrl);\r\n");
      out.write("                window.location.href = successUrl;\r\n");
      out.write("            }, 3000);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
