/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-16 07:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

String message=request.getParameter("message");
String username=(String) session.getAttribute("username");
Boolean isLoggedIn=(Boolean) session.getAttribute("isLoggedIn");
if (isLoggedIn==null) isLoggedIn=false;

String category = request.getParameter("category");
if (category == null) category = "Electronics";

// Dynamic products with detailed information
Map<String, List<Map<String, String>>> products = new HashMap<>();

// Electronics products
List<Map<String, String>> electronicsProducts = new ArrayList<>();
Map<String, String> phone = new HashMap<>();
phone.put("name", "Smartphone Pro");
phone.put("price", "₹25,999");
phone.put("image", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop&crop=center");
phone.put("description", "Latest Smartphone Pro with advanced features and 5G connectivity");
phone.put("rating", "4.5");
phone.put("id", "phone1");
electronicsProducts.add(phone);

Map<String, String> laptop = new HashMap<>();
laptop.put("name", "Gaming Laptop");
laptop.put("price", "₹65,999");
laptop.put("image", "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop&crop=center");
laptop.put("description", "High performance gaming laptop for pro gamers");
laptop.put("rating", "4.2");
laptop.put("id", "laptop1");
electronicsProducts.add(laptop);

Map<String, String> headphones = new HashMap<>();
headphones.put("name", "Wireless Headphones");
headphones.put("price", "₹8,999");
headphones.put("image", "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop&crop=center");
headphones.put("description", "Noise-cancelling wireless headphones with premium sound");
headphones.put("rating", "4.8");
headphones.put("id", "headphones1");
electronicsProducts.add(headphones);

Map<String, String> smartwatch = new HashMap<>();
smartwatch.put("name", "Smart Watch");
smartwatch.put("price", "₹12,999");
smartwatch.put("image", "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop&crop=center");
smartwatch.put("description", "Smart Watch with fitness tracking and health monitoring");
smartwatch.put("rating", "4.3");
smartwatch.put("id", "smartwatch1");
electronicsProducts.add(smartwatch);

// Fashion products
List<Map<String, String>> fashionProducts = new ArrayList<>();
Map<String, String> tshirt = new HashMap<>();
tshirt.put("name", "Premium T-Shirt");
tshirt.put("price", "₹1,299");
tshirt.put("image", "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop&crop=center");
tshirt.put("description", "Comfortable cotton t-shirt in various colors");
tshirt.put("rating", "4.4");
tshirt.put("id", "tshirt1");
fashionProducts.add(tshirt);

Map<String, String> jeans = new HashMap<>();
jeans.put("name", "Designer Jeans");
jeans.put("price", "₹2,999");
jeans.put("image", "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop&crop=center");
jeans.put("description", "Classic fit designer jeans for everyday wear");
jeans.put("rating", "4.6");
jeans.put("id", "jeans1");
fashionProducts.add(jeans);

Map<String, String> jacket = new HashMap<>();
jacket.put("name", "Winter Jacket");
jacket.put("price", "₹4,999");
jacket.put("image", "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=300&fit=crop&crop=center");
jacket.put("description", "Warm and stylish winter jacket");
jacket.put("rating", "4.7");
jacket.put("id", "jacket1");
fashionProducts.add(jacket);

// Home products
List<Map<String, String>> homeProducts = new ArrayList<>();
Map<String, String> sofa = new HashMap<>();
sofa.put("name", "Modern Sofa");
sofa.put("price", "₹35,999");
sofa.put("image", "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop&crop=center");
sofa.put("description", "Comfortable modern sofa for your living room");
sofa.put("rating", "4.5");
sofa.put("id", "sofa1");
homeProducts.add(sofa);

Map<String, String> lamp = new HashMap<>();
lamp.put("name", "Table Lamp");
lamp.put("price", "₹3,999");
lamp.put("image", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop&crop=center");
lamp.put("description", "Elegant table lamp for your workspace");
lamp.put("rating", "4.3");
lamp.put("id", "lamp1");
homeProducts.add(lamp);

// Sports products
List<Map<String, String>> sportsProducts = new ArrayList<>();
Map<String, String> basketball = new HashMap<>();
basketball.put("name", "Basketball");
basketball.put("price", "₹2,499");
basketball.put("image", "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center");
basketball.put("description", "Professional basketball for indoor and outdoor play");
basketball.put("rating", "4.6");
basketball.put("id", "basketball1");
sportsProducts.add(basketball);

Map<String, String> dumbbells = new HashMap<>();
dumbbells.put("name", "Adjustable Dumbbells");
dumbbells.put("price", "₹8,999");
dumbbells.put("image", "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center");
dumbbells.put("description", "Adjustable dumbbells for home gym workouts");
dumbbells.put("rating", "4.4");
dumbbells.put("id", "dumbbells1");
sportsProducts.add(dumbbells);

// Books products
List<Map<String, String>> booksProducts = new ArrayList<>();
Map<String, String> javaBook = new HashMap<>();
javaBook.put("name", "Java Programming Guide");
javaBook.put("price", "₹1,299");
javaBook.put("image", "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop&crop=center");
javaBook.put("description", "Comprehensive guide to Java programming");
javaBook.put("rating", "4.8");
javaBook.put("id", "javabook1");
booksProducts.add(javaBook);

Map<String, String> springBook = new HashMap<>();
springBook.put("name", "Spring Framework Guide");
springBook.put("price", "₹1,599");
springBook.put("image", "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop&crop=center");
springBook.put("description", "Complete guide to Spring Framework development");
springBook.put("rating", "4.7");
springBook.put("id", "springbook1");
booksProducts.add(springBook);

// Beauty products
List<Map<String, String>> beautyProducts = new ArrayList<>();
Map<String, String> lipstick = new HashMap<>();
lipstick.put("name", "Premium Lipstick Set");
lipstick.put("price", "₹2,999");
lipstick.put("image", "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop&crop=center");
lipstick.put("description", "Set of 6 premium lipstick shades");
lipstick.put("rating", "4.5");
lipstick.put("id", "lipstick1");
beautyProducts.add(lipstick);

Map<String, String> skincare = new HashMap<>();
skincare.put("name", "Anti-Aging Cream");
skincare.put("price", "₹3,499");
skincare.put("image", "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop&crop=center");
skincare.put("description", "Premium anti-aging skincare cream");
skincare.put("rating", "4.6");
skincare.put("id", "skincare1");
beautyProducts.add(skincare);

products.put("Electronics", electronicsProducts);
products.put("Fashion", fashionProducts);
products.put("Home", homeProducts);
products.put("Sports", sportsProducts);
products.put("Books", booksProducts);
products.put("Beauty", beautyProducts);

List<Map<String, String>> prodList = products.getOrDefault(category, new ArrayList<>());

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Products - ");
      out.print(category);
      out.write(" | ShopEasy</title>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css?v=1.0\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("        }\n");
      out.write("        .navbar {\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .nav-brand {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #667eea;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        .nav-brand i {\n");
      out.write("            font-size: 2rem;\n");
      out.write("        }\n");
      out.write("        .product-card {\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 15px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .product-card:hover {\n");
      out.write("            transform: translateY(-10px);\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("        .product-image {\n");
      out.write("            background-size: cover;\n");
      out.write("            background-position: center;\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .product-image img {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            transition: transform 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .product-card:hover .product-image img {\n");
      out.write("            transform: scale(1.1);\n");
      out.write("        }\n");
      out.write("        .product-overlay {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: rgba(0, 0, 0, 0.7);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            opacity: 0;\n");
      out.write("            transition: opacity 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .product-card:hover .product-overlay {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("        .product-price {\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #667eea;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        .product-rating {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 5px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        .product-rating i {\n");
      out.write("            color: #fbbf24;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .product-rating span {\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-left: 5px;\n");
      out.write("        }\n");
      out.write("        .section-title {\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 2.5rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2d3748;\n");
      out.write("            margin-bottom: 50px;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .section-title::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: -10px;\n");
      out.write("            left: 50%;\n");
      out.write("            transform: translateX(-50%);\n");
      out.write("            width: 80px;\n");
      out.write("            height: 4px;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            border-radius: 2px;\n");
      out.write("        }\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 25px;\n");
      out.write("            padding: 10px 25px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);\n");
      out.write("        }\n");
      out.write("        .btn-secondary {\n");
      out.write("            border-radius: 25px;\n");
      out.write("            padding: 10px 25px;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .custom-top{\n");
      out.write("            margin-top: 110px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 1200px) {\n");
      out.write("            .container {\n");
      out.write("                max-width: 100%;\n");
      out.write("                padding: 0 15px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 992px) {\n");
      out.write("            .products-grid {\n");
      out.write("                grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("                gap: 20px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .section-title {\n");
      out.write("                font-size: 2.2rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .section-title {\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("                margin-bottom: 40px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .products-grid {\n");
      out.write("                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("                gap: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-card {\n");
      out.write("                margin-bottom: 20px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-image {\n");
      out.write("                height: 200px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-info h3 {\n");
      out.write("                font-size: 1.2rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-price {\n");
      out.write("                font-size: 1.3rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 576px) {\n");
      out.write("            .container {\n");
      out.write("                padding: 0 10px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .section-title {\n");
      out.write("                font-size: 1.6rem;\n");
      out.write("                margin-bottom: 30px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .products-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("                gap: 15px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-image {\n");
      out.write("                height: 180px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-info h3 {\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-price {\n");
      out.write("                font-size: 1.2rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .btn {\n");
      out.write("                padding: 8px 20px;\n");
      out.write("                font-size: 13px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-brand {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-brand i {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 480px) {\n");
      out.write("            .section-title {\n");
      out.write("                font-size: 1.4rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-image {\n");
      out.write("                height: 160px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-info h3 {\n");
      out.write("                font-size: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-price {\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .btn {\n");
      out.write("                padding: 6px 16px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 360px) {\n");
      out.write("            .container {\n");
      out.write("                padding: 0 5px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-image {\n");
      out.write("                height: 140px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .btn {\n");
      out.write("                padding: 5px 12px;\n");
      out.write("                font-size: 11px;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("        <div class=\"nav-container\">\n");
      out.write("            <div class=\"nav-brand\">\n");
      out.write("                <i class=\"fas fa-shopping-bag\"></i>\n");
      out.write("                <span>ShopEasy</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-search d-none d-lg-flex\">\n");
      out.write("                <input type=\"text\" placeholder=\"Search products...\" class=\"search-input\">\n");
      out.write("                <button class=\"search-btn\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-links\">\n");
      out.write("                <a href=\"index.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                <a href=\"category.jsp\" class=\"nav-link\">Categories</a>\n");
      out.write("                <a href=\"product.jsp?category=");
      out.print(category);
      out.write("\" class=\"nav-link active\">Products</a>\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-link\">Cart</a>\n");
      out.write("                <a href=\"about.jsp\" class=\"nav-link\">About</a>\n");
      out.write("                <a href=\"contact.jsp\" class=\"nav-link\">Contact</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-actions d-none d-lg-flex\">\n");
      out.write("                <a href=\"#\" class=\"nav-icon\" title=\"Wishlist\"><i class=\"fas fa-heart\"></i></a>\n");
      out.write("                <a href=\"#\" class=\"nav-icon\" title=\"Shopping Cart\"><i class=\"fas fa-shopping-cart\"></i></a>\n");
      out.write("                ");
 if (isLoggedIn) { 
      out.write("\n");
      out.write("                    <div class=\"user-info\">\n");
      out.write("                        <span class=\"welcome-text\">Welcome, ");
      out.print( username );
      out.write("!</span>\n");
      out.write("                        <a href=\"logout.jsp\" class=\"nav-icon\" title=\"Logout\"><i class=\"fas fa-sign-out-alt\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <a href=\"login.jsp\" class=\"nav-icon\" title=\"Login\"><i class=\"fas fa-user\"></i></a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <button class=\"btn d-lg-none\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#navOffcanvas\" aria-controls=\"navOffcanvas\" aria-label=\"Open menu\" style=\"margin-left: 38px;\">\n");
      out.write("                <i class=\"fas fa-bars\"></i>\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("    <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"navOffcanvas\" aria-labelledby=\"navOffcanvasLabel\">\n");
      out.write("        <div class=\"offcanvas-header\">\n");
      out.write("            <h5 class=\"offcanvas-title\" id=\"navOffcanvasLabel\">ShopEasy</h5>\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"offcanvas-body d-flex flex-column\">\n");
      out.write("            <div class=\"mb-3\">\n");
      out.write("                <div class=\"d-flex align-items-center p-2 rounded\" style=\"background:#f8f9fa;\">\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control-sm me-2\" placeholder=\"Search products...\" id=\"offcanvasSearchInput\">\n");
      out.write("                    <button class=\"btn btn-primary btn-sm\" id=\"offcanvasSearchBtn\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <nav class=\"nav flex-column mb-3\">\n");
      out.write("                <a href=\"index.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                <a href=\"category.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Categories</a>\n");
      out.write("                <a href=\"product.jsp?category=");
      out.print(category);
      out.write("\" class=\"nav-link active\" data-bs-dismiss=\"offcanvas\">Products</a>\n");
      out.write("                <a href=\"cart.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Cart</a>\n");
      out.write("                <a href=\"about.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">About</a>\n");
      out.write("                <a href=\"contact.jsp\" class=\"nav-link\" data-bs-dismiss=\"offcanvas\">Contact</a>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"mt-auto d-flex align-items-center gap-3\">\n");
      out.write("                <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-heart\"></i></a>\n");
      out.write("                <a href=\"#\" class=\"text-secondary\"><i class=\"fas fa-shopping-cart\"></i></a>\n");
      out.write("                ");
 if (isLoggedIn) { 
      out.write("\n");
      out.write("                    <span class=\"text-primary fw-semibold\">Welcome, ");
      out.print( username );
      out.write("</span>\n");
      out.write("                    <a href=\"logout.jsp\" class=\"btn btn-outline-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Logout</a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <a href=\"login.jsp\" class=\"btn btn-outline-primary btn-sm\" data-bs-dismiss=\"offcanvas\">Login</a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"container custom-top\">\n");
      out.write("        <h1 class=\"section-title\">");
      out.print(category);
      out.write(" Products</h1>\n");
      out.write("        ");
 if(prodList.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"alert alert-info text-center\">\n");
      out.write("                <i class=\"fas fa-info-circle me-2\"></i>\n");
      out.write("                No products found in this category.\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                ");
 for(Map<String, String> product : prodList) { 
      out.write("\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("                    <div class=\"card product-card h-100\">\n");
      out.write("                        <div class=\"product-image\">\n");
      out.write("                            <img src=\"");
      out.print(product.get("image"));
      out.write("\" alt=\"");
      out.print(product.get("name"));
      out.write("\" loading=\"lazy\">\n");
      out.write("                            <div class=\"product-overlay\">\n");
      out.write("                                <button class=\"btn btn-light btn-sm\" data-bs-toggle=\"modal\" \n");
      out.write("                                        data-bs-target=\"#quickViewModal\" \n");
      out.write("                                        data-title=\"");
      out.print(product.get("name"));
      out.write("\"\n");
      out.write("                                        data-img=\"");
      out.print(product.get("image"));
      out.write("\"\n");
      out.write("                                        data-price=\"");
      out.print(product.get("price"));
      out.write("\"\n");
      out.write("                                        data-rating=\"");
      out.print(product.get("rating"));
      out.write("\"\n");
      out.write("                                        data-desc=\"");
      out.print(product.get("description"));
      out.write("\">\n");
      out.write("                                    <i class=\"fas fa-eye me-1\"></i>Quick View\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h5 class=\"card-title\">");
      out.print(product.get("name"));
      out.write("</h5>\n");
      out.write("                            <p class=\"product-price\">");
      out.print(product.get("price"));
      out.write("</p>\n");
      out.write("                            <div class=\"product-rating\">\n");
      out.write("                                ");
 
                                double rating = Double.parseDouble(product.get("rating"));
                                for(int i = 1; i <= 5; i++) {
                                    if(i <= rating) {
                                
      out.write("\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                ");
 } else if(i - 0.5 <= rating) { 
      out.write("\n");
      out.write("                                    <i class=\"fas fa-star-half-alt\"></i>\n");
      out.write("                                ");
 } else { 
      out.write("\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                ");
 } } 
      out.write("\n");
      out.write("                                <span>(");
      out.print(product.get("rating"));
      out.write(")</span>\n");
      out.write("                            </div>\n");
      out.write("                            <p class=\"card-text text-muted small\">");
      out.print(product.get("description"));
      out.write("</p>\n");
      out.write("                            <form action=\"cart.jsp\" method=\"post\" class=\"mt-3\">\n");
      out.write("                                <input type=\"hidden\" name=\"productId\" value=\"");
      out.print(product.get("id"));
      out.write("\" />\n");
      out.write("                                <input type=\"hidden\" name=\"productName\" value=\"");
      out.print(product.get("name"));
      out.write("\" />\n");
      out.write("                                <input type=\"hidden\" name=\"productPrice\" value=\"");
      out.print(product.get("price"));
      out.write("\" />\n");
      out.write("                                <input type=\"hidden\" name=\"productImage\" value=\"");
      out.print(product.get("image"));
      out.write("\" />\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary w-100\">\n");
      out.write("                                    <i class=\"fas fa-shopping-cart me-1\"></i>Add to Cart\n");
      out.write("                                </button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <div class=\"text-center mt-4\">\n");
      out.write("            <a href=\"category.jsp\" class=\"btn btn-secondary\">\n");
      out.write("                <i class=\"fas fa-arrow-left me-1\"></i>Back to Categories\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Quick View Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"quickViewModal\" tabindex=\"-1\" aria-labelledby=\"quickViewModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered modal-lg\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"quickViewModalLabel\">Product Details</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <div class=\"row g-3\">\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\n");
      out.write("                            <img id=\"quickViewImg\" src=\"\" class=\"w-100 rounded\" alt=\"Product Image\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\n");
      out.write("                            <h4 id=\"quickViewTitle\" class=\"mb-3\"></h4>\n");
      out.write("                            <p id=\"quickViewDesc\" class=\"mb-3\"></p>\n");
      out.write("                            <p class=\"mb-1\"><strong>Price:</strong> <span id=\"quickViewPrice\" class=\"text-primary fs-5\"></span></p>\n");
      out.write("                            <p class=\"mb-3\"><strong>Rating:</strong> <span id=\"quickViewRating\"></span></p>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success\">\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>Add to Cart\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        // Quick View Modal functionality\n");
      out.write("        document.querySelectorAll('[data-bs-target=\"#quickViewModal\"]').forEach(function(btn) {\n");
      out.write("            btn.addEventListener('click', function() {\n");
      out.write("                document.getElementById('quickViewModalLabel').textContent = this.getAttribute('data-title') || '';\n");
      out.write("                document.getElementById('quickViewImg').src = this.getAttribute('data-img') || '';\n");
      out.write("                document.getElementById('quickViewTitle').textContent = this.getAttribute('data-title') || '';\n");
      out.write("                document.getElementById('quickViewDesc').textContent = this.getAttribute('data-desc') || '';\n");
      out.write("                document.getElementById('quickViewPrice').textContent = this.getAttribute('data-price') || '';\n");
      out.write("                document.getElementById('quickViewRating').textContent = this.getAttribute('data-rating') || '';\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
