/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-17 05:06:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Sign Up - ShopEasy</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css?v=1.0\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("        <style>\r\n");
      out.write("            * {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body.signup-page {\r\n");
      out.write("                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;\r\n");
      out.write("                min-height: 100vh !important;\r\n");
      out.write("                display: flex !important;\r\n");
      out.write("                align-items: center !important;\r\n");
      out.write("                justify-content: center !important;\r\n");
      out.write("                padding: 20px !important;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-container {\r\n");
      out.write("                background: white !important;\r\n");
      out.write("                padding: 2rem !important;\r\n");
      out.write("                border-radius: 15px !important;\r\n");
      out.write("                box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1) !important;\r\n");
      out.write("                width: 100% !important;\r\n");
      out.write("                max-width: 400px !important;\r\n");
      out.write("                animation: fadeInUp 0.6s ease-out;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .header {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-bottom: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .header h1 {\r\n");
      out.write("                color: #4a5568;\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("                margin-bottom: 0.5rem;\r\n");
      out.write("                font-weight: 300;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .header p {\r\n");
      out.write("                color: #718096;\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group {\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group label {\r\n");
      out.write("                display: block;\r\n");
      out.write("                margin-bottom: 0.5rem;\r\n");
      out.write("                color: #4a5568;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group input {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 12px 16px;\r\n");
      out.write("                border: 2px solid #e2e8f0;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("                background: #f7fafc;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group input:focus {\r\n");
      out.write("                outline: none;\r\n");
      out.write("                border-color: #667eea;\r\n");
      out.write("                background: white;\r\n");
      out.write("                box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                padding: 11px 21px;\r\n");
      out.write("                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("                color: white;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 25px;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all 0.3s ease;\r\n");
      out.write("                text-transform: uppercase;\r\n");
      out.write("                letter-spacing: 0.5px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn:hover {\r\n");
      out.write("                transform: translateY(-2px);\r\n");
      out.write("                box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .link {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .link a {\r\n");
      out.write("                color: #667eea;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                transition: color 0.3s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .link a:hover {\r\n");
      out.write("                color: #764ba2;\r\n");
      out.write("                text-decoration: underline;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .message {\r\n");
      out.write("                padding: 12px 16px;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("                margin-bottom: 1rem;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .message.error {\r\n");
      out.write("                background: #fed7d7;\r\n");
      out.write("                color: #742a2a;\r\n");
      out.write("                border: 1px solid #feb2b2;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .message.success {\r\n");
      out.write("                background: #f0fff4;\r\n");
      out.write("                color: #22543d;\r\n");
      out.write("                border: 1px solid #9ae6b4;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes fadeInUp {\r\n");
      out.write("                from {\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                    transform: translateY(30px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                to {\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                    transform: translateY(0);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @media (max-width: 480px) {\r\n");
      out.write("                .form-container {\r\n");
      out.write("                    padding: 1.5rem !important;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .header h1 {\r\n");
      out.write("                    font-size: 2rem;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body class=\"signup-page\">\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                <h1><i class=\"fas fa-shopping-bag\"></i> ShopEasy</h1>\r\n");
      out.write("                <p>Create your account and start shopping!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 String error=request.getParameter("error"); if (error !=null) { 
      out.write("\r\n");
      out.write("                <div class=\"message error\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("                    ");
      out.print( error );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"signup\" method=\"post\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"fullName\"><i class=\"fas fa-user\"></i> Full Name</label>\r\n");
      out.write("                            <input type=\"text\" id=\"fullName\" name=\"fullName\" required placeholder=\"Enter your full name\"\r\n");
      out.write("                                value=\"");
      out.print( request.getParameter(" fullName") !=null ? request.getParameter("fullName")
                                : "" );
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"email\"><i class=\"fas fa-envelope\"></i> Email</label>\r\n");
      out.write("                            <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"Enter your email\"\r\n");
      out.write("                                value=\"");
      out.print( request.getParameter(" email") !=null ? request.getParameter("email") : ""
                                );
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"username\"><i class=\"fas fa-at\"></i> Username</label>\r\n");
      out.write("                            <input type=\"text\" id=\"username\" name=\"username\" required placeholder=\"Choose a username\"\r\n");
      out.write("                                value=\"");
      out.print( request.getParameter(" username") !=null ? request.getParameter("username")
                                : "" );
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"password\"><i class=\"fas fa-lock\"></i> Password</label>\r\n");
      out.write("                            <input type=\"password\" id=\"password\" name=\"password\" required\r\n");
      out.write("                                placeholder=\"Choose a password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"confirmPassword\"><i class=\"fas fa-lock\"></i> Confirm Password</label>\r\n");
      out.write("                            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required\r\n");
      out.write("                                placeholder=\"Confirm your password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            <i class=\"fas fa-user-plus\"></i> Sign Up\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"link\">\r\n");
      out.write("                        <a href=\"login.jsp\"><i class=\"fas fa-sign-in-alt\"></i> Already have an account? Sign In</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"link\">\r\n");
      out.write("                        <a href=\"index.jsp\"><i class=\"fas fa-home\"></i> Back to Home</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            document.querySelector('form').addEventListener('submit', function (e) {\r\n");
      out.write("                const fullName = document.getElementById('fullName').value;\r\n");
      out.write("                const email = document.getElementById('email').value;\r\n");
      out.write("                const username = document.getElementById('username').value;\r\n");
      out.write("                const password = document.getElementById('password').value;\r\n");
      out.write("                const confirmPassword = document.getElementById('confirmPassword').value;\r\n");
      out.write("\r\n");
      out.write("                if (fullName.length < 3) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Full Name must be at least 3 characters long');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                const emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$/;\r\n");
      out.write("                if (!emailPattern.test(email)) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Please enter a valid email address');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (username.length < 3) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Username must be at least 3 characters long');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (password.length < 6) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Password must be at least 6 characters long');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (password !== confirmPassword) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Passwords do not match');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                const btn = document.querySelector('.btn');\r\n");
      out.write("                btn.textContent = 'Signing Up...';\r\n");
      out.write("                btn.disabled = true;\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
